server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cas?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 10
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
    password: Greatwall!@#403
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: "classpath*:/mapper/*.xml"
  global-config:
    db-config:
      id-type: auto
logging:
  config: classpath:logback.xml

